//init
export const INIT_LOADING_START = "INIT_LOADING_START"
export const INIT_LOADING_END = "INIT_LOADING_END"
export const INIT_ERROR_TRUE = "INIT_ERROR_TRUE"
export const INIT_ERROR_FALSE = "INIT_ERROR_FALSE"

//allstocks
export const GET_ALL_STOCKS = "GET_ALL_STOCKS"

//watchlist
export const WATCHLIST_ADD = "WATCHLIST_ADD"
export const WATCHLIST_REMOVE = "WATCHLIST_REMOVE"
export const WATCHLIST_SET_ACTIVE = "WATCHLIST_SET_ACTIVE"
export const WATCHLIST_REMOVE_ACTIVE = "WATCHLIST_REMOVE_ACTIVE"
export const WATCHLIST_MOVE = "WATCLHIST_MOVE"
export const WATCHLIST_UPDATE = "WATCHLIST_UPDATE"

//stockData
export const DATA_GET_INTRADAY = "DATA_GET_INTRADAY"
export const DATA_GET_QUOTE ="DATA_GET_QUOTE"
export const SET_NEWS = "SET_NEWS"
export const DATA_REMOVE = "DATA_REMOVE"
export const DATA_GET_CHART = "DATA_GET_CHART"
export const DATA_CHART_RESET= "DATA_CHART_RESET"

//news
export const NEWS_MODAL_SHOW = 'NEWS_MODAL_SHOW'
export const NEWS_MODAL_HIDE = 'NEWS_MODAL_HIDE'
export const NEWS_LINK_SET = 'NEWS_LINK_SET'
export const NEWS_LINK_RESET = 'NEWS_LINK_RESET'
export const NEWS_RESET = "NEWS_RESET"

//market open
export const GET_MARKET_OPEN = 'GET_MARKET_OPEN'
export const INCREMENT_MARKET = "INCREMENT_MARKET"